# Generated by Django 5.0.6 on 2024-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service_app', '0005_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
