# Generated by Django 5.0.6 on 2024-05-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service_app', '0006_servicetype_extra_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
