# Generated by Django 5.0.6 on 2024-05-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service_app', '0007_remove_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cleaning_service_app.client'),
        ),
    ]
