# Generated by Django 5.0.6 on 2024-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service_app', '0009_alter_answer_date_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
